In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_excel('food_access.xls', sheet_name = None)
access = df['ACCESS']
access = access[['FIPS', 'State', 'County', 'LACCESS_POP15']]
access

       FIPS State       County  LACCESS_POP15
0      1001    AL      Autauga   17496.693038
1      1003    AL      Baldwin   30561.264430
2      1005    AL      Barbour    6069.523628
3      1007    AL         Bibb     969.378841
4      1009    AL       Blount    3724.428242
5      1011    AL      Bullock    4141.900365
6      1013    AL       Butler    1304.328756
7      1015    AL      Calhoun   27785.986765
8      1017    AL     Chambers    7131.505717
9      1019    AL     Cherokee     103.522499
10     1021    AL      Chilton    1469.899110
11     1023    AL      Choctaw    2702.895199
12     1025    AL       Clarke    5712.926332
13     1027    AL         Clay     642.740920
14     1029    AL     Cleburne     789.535143
15     1031    AL       Coffee   10486.085980
16     1033    AL      Colbert   11095.666304
17     1035    AL      Conecuh    3558.359440
18     1037    AL        Coosa    2828.930334
19     1039    AL    Covington    3769.122248
20     1041    AL     Crenshaw    5278.966487
21     1043    AL      Cullman    5900.270202
22     1045    AL         Dale   14036.970117
23     1047    AL       Dallas    7640.056868
24     1049    AL       DeKalb    2679.852662
25     1051    AL       Elmore   15064.366588
26     1053    AL     Escambia    5058.775403
27     1055    AL       Etowah   23289.826821
28     1057    AL      Fayette     407.386753
29     1059    AL     Franklin    3663.441736
...     ...   ...          ...            ...
3113  55129    WI     Washburn    2822.112627
3114  55131    WI   Washington   25036.823321
3115  55133    WI     Waukesha  139440.964039
3116  55135    WI      Waupaca    6215.256992
3117  55137    WI     Waushara     400.713747
3118  55139    WI    Winnebago   34475.392629
3119  55141    WI         Wood   17934.342793
3120  56001    WY       Albany   13449.746587
3121  56003    WY     Big Horn    2176.423005
3122  56005    WY     Campbell   10762.158102
3123  56007    WY       Carbon    8588.988510
3124  56009    WY     Converse    1740.297012
3125  56011    WY        Crook    1795.576875
3126  56013    WY      Fremont    5269.600430
3127  56015    WY       Goshen    3457.690654
3128  56017    WY  Hot Springs     394.149836
3129  56019    WY      Johnson    1713.579912
3130  56021    WY      Laramie   31924.453769
3131  56023    WY      Lincoln    2478.628436
3132  56025    WY      Natrona   32267.100162
3133  56027    WY     Niobrara     544.734192
3134  56029    WY         Park    5818.211156
3135  56031    WY       Platte    1798.839152
3136  56033    WY     Sheridan   12976.661539
3137  56035    WY     Sublette    1943.267822
3138  56037    WY   Sweetwater   18934.737809
3139  56039    WY        Teton    6212.390430
3140  56041    WY        Uinta    4686.017653
3141  56043    WY     Washakie     931.411647
3142  56045    WY       Weston    1237.267037

[3143 rows x 4 columns]

In [3]:
stores = df['STORES']
stores = stores[['FIPS', 'State', 'County', 'GROC14']]
stores

       FIPS State       County  GROC14
0      1001    AL      Autauga       4
1      1003    AL      Baldwin      29
2      1005    AL      Barbour       5
3      1007    AL         Bibb       5
4      1009    AL       Blount       6
5      1011    AL      Bullock       2
6      1013    AL       Butler       3
7      1015    AL      Calhoun      27
8      1017    AL     Chambers       7
9      1019    AL     Cherokee       5
10     1021    AL      Chilton       6
11     1023    AL      Choctaw       3
12     1025    AL       Clarke       5
13     1027    AL         Clay       3
14     1029    AL     Cleburne       2
15     1031    AL       Coffee       5
16     1033    AL      Colbert      10
17     1035    AL      Conecuh       2
18     1037    AL        Coosa       1
19     1039    AL    Covington       6
20     1041    AL     Crenshaw       3
21     1043    AL      Cullman      15
22     1045    AL         Dale       8
23     1047    AL       Dallas       8
24     1049    AL       DeKalb      14
25     1051    AL       Elmore      10
26     1053    AL     Escambia       4
27     1055    AL       Etowah      13
28     1057    AL      Fayette       5
29     1059    AL     Franklin       8
...     ...   ...          ...     ...
3113  55129    WI     Washburn       6
3114  55131    WI   Washington      18
3115  55133    WI     Waukesha      66
3116  55135    WI      Waupaca       9
3117  55137    WI     Waushara       8
3118  55139    WI    Winnebago      15
3119  55141    WI         Wood      10
3120  56001    WY       Albany       3
3121  56003    WY     Big Horn       3
3122  56005    WY     Campbell       5
3123  56007    WY       Carbon       3
3124  56009    WY     Converse       3
3125  56011    WY        Crook       3
3126  56013    WY      Fremont       8
3127  56015    WY       Goshen       2
3128  56017    WY  Hot Springs       1
3129  56019    WY      Johnson       5
3130  56021    WY      Laramie       8
3131  56023    WY      Lincoln       8
3132  56025    WY      Natrona       7
3133  56027    WY     Niobrara       1
3134  56029    WY         Park       4
3135  56031    WY       Platte       3
3136  56033    WY     Sheridan       6
3137  56035    WY     Sublette       3
3138  56037    WY   Sweetwater       5
3139  56039    WY        Teton      11
3140  56041    WY        Uinta       2
3141  56043    WY     Washakie       2
3142  56045    WY       Weston       4

[3143 rows x 4 columns]

In [4]:
restaurants = df['RESTAURANTS']
restaurants = restaurants[['FIPS', 'State', 'County', 'FFR14', 'FSR14']]
restaurants

       FIPS State       County  FFR14  FSR14
0      1001    AL      Autauga     36     29
1      1003    AL      Baldwin    132    221
2      1005    AL      Barbour     22     15
3      1007    AL         Bibb      5      5
4      1009    AL       Blount     21     15
5      1011    AL      Bullock      3      1
6      1013    AL       Butler     17     10
7      1015    AL      Calhoun    103     77
8      1017    AL     Chambers     26     16
9      1019    AL     Cherokee     15     11
10     1021    AL      Chilton     20     18
11     1023    AL      Choctaw      6      5
12     1025    AL       Clarke     26     15
13     1027    AL         Clay      4      6
14     1029    AL     Cleburne      8      2
15     1031    AL       Coffee     34     28
16     1033    AL      Colbert     52     38
17     1035    AL      Conecuh      7      4
18     1037    AL        Coosa      1      0
19     1039    AL    Covington     24     18
20     1041    AL     Crenshaw      5      6
21     1043    AL      Cullman     53     48
22     1045    AL         Dale     34     30
23     1047    AL       Dallas     19     15
24     1049    AL       DeKalb     43     31
25     1051    AL       Elmore     45     38
26     1053    AL     Escambia     27     20
27     1055    AL       Etowah     79     57
28     1057    AL      Fayette      9      9
29     1059    AL     Franklin     18     16
...     ...   ...          ...    ...    ...
3113  55129    WI     Washburn      5     34
3114  55131    WI   Washington     75     77
3115  55133    WI     Waukesha    258    299
3116  55135    WI      Waupaca     37     49
3117  55137    WI     Waushara      8     32
3118  55139    WI    Winnebago     92    123
3119  55141    WI         Wood     41     66
3120  56001    WY       Albany     27     35
3121  56003    WY     Big Horn      5      7
3122  56005    WY     Campbell     33     31
3123  56007    WY       Carbon      7     26
3124  56009    WY     Converse      8     17
3125  56011    WY        Crook      6     13
3126  56013    WY      Fremont     20     39
3127  56015    WY       Goshen     11     12
3128  56017    WY  Hot Springs      5      8
3129  56019    WY      Johnson      7      8
3130  56021    WY      Laramie     65     53
3131  56023    WY      Lincoln     12     22
3132  56025    WY      Natrona     53     64
3133  56027    WY     Niobrara      3      3
3134  56029    WY         Park     18     40
3135  56031    WY       Platte      5     13
3136  56033    WY     Sheridan     22     30
3137  56035    WY     Sublette      3     12
3138  56037    WY   Sweetwater     33     32
3139  56039    WY        Teton     23     55
3140  56041    WY        Uinta     16     16
3141  56043    WY     Washakie      6     11
3142  56045    WY       Weston      3     11

[3143 rows x 5 columns]

In [5]:
local = df['LOCAL']
local = local[['FIPS', 'State', 'County', 'FMRKT16']]
local

       FIPS State       County  FMRKT16
0      1001    AL      Autauga        1
1      1003    AL      Baldwin        4
2      1005    AL      Barbour        4
3      1007    AL         Bibb        1
4      1009    AL       Blount        1
5      1011    AL      Bullock        1
6      1013    AL       Butler        2
7      1015    AL      Calhoun        2
8      1017    AL     Chambers        1
9      1019    AL     Cherokee        1
10     1021    AL      Chilton        0
11     1023    AL      Choctaw        1
12     1025    AL       Clarke        2
13     1027    AL         Clay        2
14     1029    AL     Cleburne        1
15     1031    AL       Coffee        1
16     1033    AL      Colbert        3
17     1035    AL      Conecuh        1
18     1037    AL        Coosa        0
19     1039    AL    Covington        2
20     1041    AL     Crenshaw        1
21     1043    AL      Cullman        1
22     1045    AL         Dale        2
23     1047    AL       Dallas        1
24     1049    AL       DeKalb        2
25     1051    AL       Elmore        2
26     1053    AL     Escambia        3
27     1055    AL       Etowah        3
28     1057    AL      Fayette        1
29     1059    AL     Franklin        2
...     ...   ...          ...      ...
3113  55129    WI     Washburn        1
3114  55131    WI   Washington        5
3115  55133    WI     Waukesha       12
3116  55135    WI      Waupaca        1
3117  55137    WI     Waushara        0
3118  55139    WI    Winnebago        8
3119  55141    WI         Wood        5
3120  56001    WY       Albany        2
3121  56003    WY     Big Horn        3
3122  56005    WY     Campbell        1
3123  56007    WY       Carbon        1
3124  56009    WY     Converse        1
3125  56011    WY        Crook        0
3126  56013    WY      Fremont        6
3127  56015    WY       Goshen        3
3128  56017    WY  Hot Springs        1
3129  56019    WY      Johnson        1
3130  56021    WY      Laramie        3
3131  56023    WY      Lincoln        2
3132  56025    WY      Natrona        3
3133  56027    WY     Niobrara        1
3134  56029    WY         Park        3
3135  56031    WY       Platte        2
3136  56033    WY     Sheridan        2
3137  56035    WY     Sublette        1
3138  56037    WY   Sweetwater        2
3139  56039    WY        Teton        3
3140  56041    WY        Uinta        2
3141  56043    WY     Washakie        2
3142  56045    WY       Weston        2

[3143 rows x 4 columns]

In [6]:
health = df['HEALTH']
health = health[['FIPS', 'State', 'County', 'PCT_DIABETES_ADULTS13', 'PCT_OBESE_ADULTS13']]
health

       FIPS State       County  PCT_DIABETES_ADULTS13  PCT_OBESE_ADULTS13
0      1001    AL      Autauga                   13.0                34.1
1      1003    AL      Baldwin                   10.4                27.4
2      1005    AL      Barbour                   18.4                44.4
3      1007    AL         Bibb                   14.8                40.3
4      1009    AL       Blount                   14.1                34.6
5      1011    AL      Bullock                   19.6                43.0
6      1013    AL       Butler                   17.7                36.3
7      1015    AL      Calhoun                   14.9                32.2
8      1017    AL     Chambers                   16.4                39.7
9      1019    AL     Cherokee                   13.3                33.6
10     1021    AL      Chilton                   13.3                35.9
11     1023    AL      Choctaw                   18.1                40.8
12     1025    AL       Clarke                   16.3                38.2
13     1027    AL         Clay                   14.6                37.3
14     1029    AL     Cleburne                   12.6                30.0
15     1031    AL       Coffee                   15.9                33.7
16     1033    AL      Colbert                   18.7                37.5
17     1035    AL      Conecuh                   17.4                36.4
18     1037    AL        Coosa                   17.3                39.7
19     1039    AL    Covington                   14.7                34.0
20     1041    AL     Crenshaw                   16.5                39.7
21     1043    AL      Cullman                   14.4                33.4
22     1045    AL         Dale                   14.1                36.5
23     1047    AL       Dallas                   19.0                40.8
24     1049    AL       DeKalb                   13.4                30.4
25     1051    AL       Elmore                   13.4                35.4
26     1053    AL     Escambia                   17.8                37.7
27     1055    AL       Etowah                   16.8                35.1
28     1057    AL      Fayette                   15.1                33.7
29     1059    AL     Franklin                   13.9                33.2
...     ...   ...          ...                    ...                 ...
3113  55129    WI     Washburn                   10.5                30.8
3114  55131    WI   Washington                    8.2                29.2
3115  55133    WI     Waukesha                    7.9                27.5
3116  55135    WI      Waupaca                    9.9                28.5
3117  55137    WI     Waushara                   10.6                32.9
3118  55139    WI    Winnebago                    8.6                31.9
3119  55141    WI         Wood                    8.1                32.3
3120  56001    WY       Albany                    6.9                23.3
3121  56003    WY     Big Horn                   11.7                28.9
3122  56005    WY     Campbell                    7.0                34.3
3123  56007    WY       Carbon                    8.2                28.2
3124  56009    WY     Converse                   10.2                28.3
3125  56011    WY        Crook                    8.9                25.9
3126  56013    WY      Fremont                    9.6                28.3
3127  56015    WY       Goshen                    9.0                29.9
3128  56017    WY  Hot Springs                   11.0                27.0
3129  56019    WY      Johnson                    8.7                21.1
3130  56021    WY      Laramie                   10.1                29.7
3131  56023    WY      Lincoln                    8.6                25.6
3132  56025    WY      Natrona                    9.0                29.4
3133  56027    WY     Niobrara                    8.4                25.5
3134  56029    WY         Park                    8.0                25.5
3135  56031    WY       Platte                    8.8                28.0
3136  56033    WY     Sheridan                    9.8                23.3
3137  56035    WY     Sublette                    6.9                23.5
3138  56037    WY   Sweetwater                    8.1                31.7
3139  56039    WY        Teton                    4.8                12.7
3140  56041    WY        Uinta                    9.0                27.9
3141  56043    WY     Washakie                   12.0                27.7
3142  56045    WY       Weston                   10.0                29.2

[3143 rows x 5 columns]

In [7]:
socio_economic = df['SOCIOECONOMIC']
socio_economic = socio_economic[['FIPS', 'State', 'County', 'MEDHHINC15', 'POVRATE15']]
socio_economic

       FIPS State       County  MEDHHINC15  POVRATE15
0      1001    AL      Autauga     56580.0       12.7
1      1003    AL      Baldwin     52387.0       12.9
2      1005    AL      Barbour     31433.0       32.0
3      1007    AL         Bibb     40767.0       22.2
4      1009    AL       Blount     50487.0       14.7
5      1011    AL      Bullock     28251.0       39.6
6      1013    AL       Butler     33868.0       25.8
7      1015    AL      Calhoun     42091.0       20.0
8      1017    AL     Chambers     35560.0       22.4
9      1019    AL     Cherokee     39144.0       19.4
10     1021    AL      Chilton     42767.0       20.2
11     1023    AL      Choctaw     35089.0       24.4
12     1025    AL       Clarke     37317.0       22.2
13     1027    AL         Clay     38908.0       18.4
14     1029    AL     Cleburne     42136.0       18.9
15     1031    AL       Coffee     46858.0       16.2
16     1033    AL      Colbert     41171.0       18.1
17     1035    AL      Conecuh     29981.0       28.3
18     1037    AL        Coosa     36078.0       20.3
19     1039    AL    Covington     36355.0       22.3
20     1041    AL     Crenshaw     36759.0       19.9
21     1043    AL      Cullman     39290.0       19.4
22     1045    AL         Dale     45294.0       18.5
23     1047    AL       Dallas     29682.0       34.6
24     1049    AL       DeKalb     37305.0       20.6
25     1051    AL       Elmore     53548.0       14.0
26     1053    AL     Escambia     36840.0       24.4
27     1055    AL       Etowah     42145.0       19.0
28     1057    AL      Fayette     37085.0       20.4
29     1059    AL     Franklin     38535.0       21.1
...     ...   ...          ...         ...        ...
3113  55129    WI     Washburn     45043.0       13.5
3114  55131    WI   Washington     70778.0        5.3
3115  55133    WI     Waukesha     78689.0        4.7
3116  55135    WI      Waupaca     54849.0       10.7
3117  55137    WI     Waushara     49912.0       11.8
3118  55139    WI    Winnebago     52725.0       11.3
3119  55141    WI         Wood     51025.0       11.3
3120  56001    WY       Albany     44455.0       20.1
3121  56003    WY     Big Horn     50056.0       12.1
3122  56005    WY     Campbell     83042.0        7.5
3123  56007    WY       Carbon     60209.0       11.4
3124  56009    WY     Converse     70307.0        8.5
3125  56011    WY        Crook     64851.0        7.7
3126  56013    WY      Fremont     52408.0       12.9
3127  56015    WY       Goshen     48146.0       15.1
3128  56017    WY  Hot Springs     46021.0       11.9
3129  56019    WY      Johnson     56845.0        8.2
3130  56021    WY      Laramie     59147.0       10.6
3131  56023    WY      Lincoln     62364.0        8.8
3132  56025    WY      Natrona     56703.0       11.0
3133  56027    WY     Niobrara     46693.0       13.3
3134  56029    WY         Park     55527.0        9.6
3135  56031    WY       Platte     51863.0       11.7
3136  56033    WY     Sheridan     57122.0        9.5
3137  56035    WY     Sublette     77581.0        6.1
3138  56037    WY   Sweetwater     71867.0        8.5
3139  56039    WY        Teton     83290.0        6.6
3140  56041    WY        Uinta     62968.0        9.8
3141  56043    WY     Washakie     56088.0       11.2
3142  56045    WY       Weston     60986.0        9.8

[3143 rows x 5 columns]

In [8]:
access = access.merge(stores, on=["FIPS", "State", "County"], how="outer")
access

       FIPS State       County  LACCESS_POP15  GROC14
0      1001    AL      Autauga   17496.693038       4
1      1003    AL      Baldwin   30561.264430      29
2      1005    AL      Barbour    6069.523628       5
3      1007    AL         Bibb     969.378841       5
4      1009    AL       Blount    3724.428242       6
5      1011    AL      Bullock    4141.900365       2
6      1013    AL       Butler    1304.328756       3
7      1015    AL      Calhoun   27785.986765      27
8      1017    AL     Chambers    7131.505717       7
9      1019    AL     Cherokee     103.522499       5
10     1021    AL      Chilton    1469.899110       6
11     1023    AL      Choctaw    2702.895199       3
12     1025    AL       Clarke    5712.926332       5
13     1027    AL         Clay     642.740920       3
14     1029    AL     Cleburne     789.535143       2
15     1031    AL       Coffee   10486.085980       5
16     1033    AL      Colbert   11095.666304      10
17     1035    AL      Conecuh    3558.359440       2
18     1037    AL        Coosa    2828.930334       1
19     1039    AL    Covington    3769.122248       6
20     1041    AL     Crenshaw    5278.966487       3
21     1043    AL      Cullman    5900.270202      15
22     1045    AL         Dale   14036.970117       8
23     1047    AL       Dallas    7640.056868       8
24     1049    AL       DeKalb    2679.852662      14
25     1051    AL       Elmore   15064.366588      10
26     1053    AL     Escambia    5058.775403       4
27     1055    AL       Etowah   23289.826821      13
28     1057    AL      Fayette     407.386753       5
29     1059    AL     Franklin    3663.441736       8
...     ...   ...          ...            ...     ...
3113  55129    WI     Washburn    2822.112627       6
3114  55131    WI   Washington   25036.823321      18
3115  55133    WI     Waukesha  139440.964039      66
3116  55135    WI      Waupaca    6215.256992       9
3117  55137    WI     Waushara     400.713747       8
3118  55139    WI    Winnebago   34475.392629      15
3119  55141    WI         Wood   17934.342793      10
3120  56001    WY       Albany   13449.746587       3
3121  56003    WY     Big Horn    2176.423005       3
3122  56005    WY     Campbell   10762.158102       5
3123  56007    WY       Carbon    8588.988510       3
3124  56009    WY     Converse    1740.297012       3
3125  56011    WY        Crook    1795.576875       3
3126  56013    WY      Fremont    5269.600430       8
3127  56015    WY       Goshen    3457.690654       2
3128  56017    WY  Hot Springs     394.149836       1
3129  56019    WY      Johnson    1713.579912       5
3130  56021    WY      Laramie   31924.453769       8
3131  56023    WY      Lincoln    2478.628436       8
3132  56025    WY      Natrona   32267.100162       7
3133  56027    WY     Niobrara     544.734192       1
3134  56029    WY         Park    5818.211156       4
3135  56031    WY       Platte    1798.839152       3
3136  56033    WY     Sheridan   12976.661539       6
3137  56035    WY     Sublette    1943.267822       3
3138  56037    WY   Sweetwater   18934.737809       5
3139  56039    WY        Teton    6212.390430      11
3140  56041    WY        Uinta    4686.017653       2
3141  56043    WY     Washakie     931.411647       2
3142  56045    WY       Weston    1237.267037       4

[3143 rows x 5 columns]

In [9]:
access = access.merge(restaurants, on=["FIPS", "State", "County"], how="outer")
access

       FIPS State       County  LACCESS_POP15  GROC14  FFR14  FSR14
0      1001    AL      Autauga   17496.693038       4     36     29
1      1003    AL      Baldwin   30561.264430      29    132    221
2      1005    AL      Barbour    6069.523628       5     22     15
3      1007    AL         Bibb     969.378841       5      5      5
4      1009    AL       Blount    3724.428242       6     21     15
5      1011    AL      Bullock    4141.900365       2      3      1
6      1013    AL       Butler    1304.328756       3     17     10
7      1015    AL      Calhoun   27785.986765      27    103     77
8      1017    AL     Chambers    7131.505717       7     26     16
9      1019    AL     Cherokee     103.522499       5     15     11
10     1021    AL      Chilton    1469.899110       6     20     18
11     1023    AL      Choctaw    2702.895199       3      6      5
12     1025    AL       Clarke    5712.926332       5     26     15
13     1027    AL         Clay     642.740920       3      4      6
14     1029    AL     Cleburne     789.535143       2      8      2
15     1031    AL       Coffee   10486.085980       5     34     28
16     1033    AL      Colbert   11095.666304      10     52     38
17     1035    AL      Conecuh    3558.359440       2      7      4
18     1037    AL        Coosa    2828.930334       1      1      0
19     1039    AL    Covington    3769.122248       6     24     18
20     1041    AL     Crenshaw    5278.966487       3      5      6
21     1043    AL      Cullman    5900.270202      15     53     48
22     1045    AL         Dale   14036.970117       8     34     30
23     1047    AL       Dallas    7640.056868       8     19     15
24     1049    AL       DeKalb    2679.852662      14     43     31
25     1051    AL       Elmore   15064.366588      10     45     38
26     1053    AL     Escambia    5058.775403       4     27     20
27     1055    AL       Etowah   23289.826821      13     79     57
28     1057    AL      Fayette     407.386753       5      9      9
29     1059    AL     Franklin    3663.441736       8     18     16
...     ...   ...          ...            ...     ...    ...    ...
3113  55129    WI     Washburn    2822.112627       6      5     34
3114  55131    WI   Washington   25036.823321      18     75     77
3115  55133    WI     Waukesha  139440.964039      66    258    299
3116  55135    WI      Waupaca    6215.256992       9     37     49
3117  55137    WI     Waushara     400.713747       8      8     32
3118  55139    WI    Winnebago   34475.392629      15     92    123
3119  55141    WI         Wood   17934.342793      10     41     66
3120  56001    WY       Albany   13449.746587       3     27     35
3121  56003    WY     Big Horn    2176.423005       3      5      7
3122  56005    WY     Campbell   10762.158102       5     33     31
3123  56007    WY       Carbon    8588.988510       3      7     26
3124  56009    WY     Converse    1740.297012       3      8     17
3125  56011    WY        Crook    1795.576875       3      6     13
3126  56013    WY      Fremont    5269.600430       8     20     39
3127  56015    WY       Goshen    3457.690654       2     11     12
3128  56017    WY  Hot Springs     394.149836       1      5      8
3129  56019    WY      Johnson    1713.579912       5      7      8
3130  56021    WY      Laramie   31924.453769       8     65     53
3131  56023    WY      Lincoln    2478.628436       8     12     22
3132  56025    WY      Natrona   32267.100162       7     53     64
3133  56027    WY     Niobrara     544.734192       1      3      3
3134  56029    WY         Park    5818.211156       4     18     40
3135  56031    WY       Platte    1798.839152       3      5     13
3136  56033    WY     Sheridan   12976.661539       6     22     30
3137  56035    WY     Sublette    1943.267822       3      3     12
3138  56037    WY   Sweetwater   18934.737809       5     33     32
3139  56039    WY        Teton    6212.390430      11     23     55
3140  56041    WY        Uinta    4686.017653       2     16     16
3141  56043    WY     Washakie     931.411647       2      6     11
3142  56045    WY       Weston    1237.267037       4      3     11

[3143 rows x 7 columns]

In [10]:
access = access.merge(local, on=["FIPS", "State", "County"], how="outer")
access

       FIPS State       County  LACCESS_POP15  GROC14  FFR14  FSR14  FMRKT16
0      1001    AL      Autauga   17496.693038       4     36     29        1
1      1003    AL      Baldwin   30561.264430      29    132    221        4
2      1005    AL      Barbour    6069.523628       5     22     15        4
3      1007    AL         Bibb     969.378841       5      5      5        1
4      1009    AL       Blount    3724.428242       6     21     15        1
5      1011    AL      Bullock    4141.900365       2      3      1        1
6      1013    AL       Butler    1304.328756       3     17     10        2
7      1015    AL      Calhoun   27785.986765      27    103     77        2
8      1017    AL     Chambers    7131.505717       7     26     16        1
9      1019    AL     Cherokee     103.522499       5     15     11        1
10     1021    AL      Chilton    1469.899110       6     20     18        0
11     1023    AL      Choctaw    2702.895199       3      6      5        1
12     1025    AL       Clarke    5712.926332       5     26     15        2
13     1027    AL         Clay     642.740920       3      4      6        2
14     1029    AL     Cleburne     789.535143       2      8      2        1
15     1031    AL       Coffee   10486.085980       5     34     28        1
16     1033    AL      Colbert   11095.666304      10     52     38        3
17     1035    AL      Conecuh    3558.359440       2      7      4        1
18     1037    AL        Coosa    2828.930334       1      1      0        0
19     1039    AL    Covington    3769.122248       6     24     18        2
20     1041    AL     Crenshaw    5278.966487       3      5      6        1
21     1043    AL      Cullman    5900.270202      15     53     48        1
22     1045    AL         Dale   14036.970117       8     34     30        2
23     1047    AL       Dallas    7640.056868       8     19     15        1
24     1049    AL       DeKalb    2679.852662      14     43     31        2
25     1051    AL       Elmore   15064.366588      10     45     38        2
26     1053    AL     Escambia    5058.775403       4     27     20        3
27     1055    AL       Etowah   23289.826821      13     79     57        3
28     1057    AL      Fayette     407.386753       5      9      9        1
29     1059    AL     Franklin    3663.441736       8     18     16        2
...     ...   ...          ...            ...     ...    ...    ...      ...
3113  55129    WI     Washburn    2822.112627       6      5     34        1
3114  55131    WI   Washington   25036.823321      18     75     77        5
3115  55133    WI     Waukesha  139440.964039      66    258    299       12
3116  55135    WI      Waupaca    6215.256992       9     37     49        1
3117  55137    WI     Waushara     400.713747       8      8     32        0
3118  55139    WI    Winnebago   34475.392629      15     92    123        8
3119  55141    WI         Wood   17934.342793      10     41     66        5
3120  56001    WY       Albany   13449.746587       3     27     35        2
3121  56003    WY     Big Horn    2176.423005       3      5      7        3
3122  56005    WY     Campbell   10762.158102       5     33     31        1
3123  56007    WY       Carbon    8588.988510       3      7     26        1
3124  56009    WY     Converse    1740.297012       3      8     17        1
3125  56011    WY        Crook    1795.576875       3      6     13        0
3126  56013    WY      Fremont    5269.600430       8     20     39        6
3127  56015    WY       Goshen    3457.690654       2     11     12        3
3128  56017    WY  Hot Springs     394.149836       1      5      8        1
3129  56019    WY      Johnson    1713.579912       5      7      8        1
3130  56021    WY      Laramie   31924.453769       8     65     53        3
3131  56023    WY      Lincoln    2478.628436       8     12     22        2
3132  56025    WY      Natrona   32267.100162       7     53     64        3
3133  56027    WY     Niobrara     544.734192       1      3      3        1
3134  56029    WY         Park    5818.211156       4     18     40        3
3135  56031    WY       Platte    1798.839152       3      5     13        2
3136  56033    WY     Sheridan   12976.661539       6     22     30        2
3137  56035    WY     Sublette    1943.267822       3      3     12        1
3138  56037    WY   Sweetwater   18934.737809       5     33     32        2
3139  56039    WY        Teton    6212.390430      11     23     55        3
3140  56041    WY        Uinta    4686.017653       2     16     16        2
3141  56043    WY     Washakie     931.411647       2      6     11        2
3142  56045    WY       Weston    1237.267037       4      3     11        2

[3143 rows x 8 columns]

In [11]:
access = access.merge(health, on=["FIPS", "State", "County"], how="outer")
access

,FIPS,State,County,LACCESS_POP15,GROC14,FFR14,FSR14,FMRKT16,PCT_DIABETES_ADULTS13,PCT_OBESE_ADULTS13
0,1001,AL,Autauga,17496.693038,4,36,29,1,13.0,34.1
1,1003,AL,Baldwin,30561.264430,29,132,221,4,10.4,27.4
2,1005,AL,Barbour,6069.523628,5,22,15,4,18.4,44.4
3,1007,AL,Bibb,969.378841,5,5,5,1,14.8,40.3
4,1009,AL,Blount,3724.428242,6,21,15,1,14.1,34.6
5,1011,AL,Bullock,4141.900365,2,3,1,1,19.6,43.0
6,1013,AL,Butler,1304.328756,3,17,10,2,17.7,36.3
7,1015,AL,Calhoun,27785.986765,27,103,77,2,14.9,32.2
8,1017,AL,Chambers,7131.505717,7,26,16,1,16.4,39.7
9,1019,AL,Cherokee,103.522499,5,15,11,1,13.3,33.6
10,1021,AL,Chilton,1469.899110,6,20,18,0,13.3,35.9
11,1023,AL,Choctaw,2702.895199,3,6,5,1,18.1,40.8
12,1025,AL,Clarke,5712.926332,5,26,15,2,16.3,38.2
13,1027,AL,Clay,642.740920,3,4,6,2,14.6,37.3
14,1029,AL,Cleburne,789.535143,2,8,2,1,12.6,30.0
15,1031,AL,Coffee,10486.085980,5,34,28,1,15.9,33.7
16,1033,AL,Colbert,11095.666304,10,52,38,3,18.7,37.5
17,1035,AL,Conecuh,3558.359440,2,7,4,1,17.4,36.4
18,1037,AL,Coosa,2828.930334,1,1,0,0,17.3,39.7
19,1039,AL,Covington,3769.122248,6,24,18,2,14.7,34.0
20,1041,AL,Crenshaw,5278.966487,3,5,6,1,16.5,39.7
21,1043,AL,Cullman,5900.270202,15,53,48,1,14.4,33.4
22,1045,AL,Dale,14036.970117,8,34,30,2,14.1,36.5
23,1047,AL,Dallas,7640.056868,8,19,15,1,19.0,40.8
24,1049,AL,DeKalb,2679.852662,14,43,31,2,13.4,30.4
25,1051,AL,Elmore,15064.366588,10,45,38,2,13.4,35.4
26,1053,AL,Escambia,5058.775403,4,27,20,3,17.8,37.7
27,1055,AL,Etowah,23289.826821,13,79,57,3,16.8,35.1
28,1057,AL,Fayette,407.386753,5,9,9,1,15.1,33.7
29,1059,AL,Franklin,3663.441736,8,18,16,2,13.9,33.2
...,...,...,...,...,...,...,...,...,...,...
3113,55129,WI,Washburn,2822.112627,6,5,34,1,10.5,30.8
3114,55131,WI,Washington,25036.823321,18,75,77,5,8.2,29.2
3115,55133,WI,Waukesha,139440.964039,66,258,299,12,7.9,27.5
3116,55135,WI,Waupaca,6215.256992,9,37,49,1,9.9,28.5
3117,55137,WI,Waushara,400.713747,8,8,32,0,10.6,32.9
3118,55139,WI,Winnebago,34475.392629,15,92,123,8,8.6,31.9
3119,55141,WI,Wood,17934.342793,10,41,66,5,8.1,32.3
3120,56001,WY,Albany,13449.746587,3,27,35,2,6.9,23.3
3121,56003,WY,Big Horn,2176.423005,3,5,7,3,11.7,28.9
3122,56005,WY,Campbell,10762.158102,5,33,31,1,7.0,34.3
3123,56007,WY,Carbon,8588.988510,3,7,26,1,8.2,28.2
3124,56009,WY,Converse,1740.297012,3,8,17,1,10.2,28.3
3125,56011,WY,Crook,1795.576875,3,6,13,0,8.9,25.9
3126,56013,WY,Fremont,5269.600430,8,20,39,6,9.6,28.3
3127,56015,WY,Goshen,3457.690654,2,11,12,3,9.0,29.9
3128,56017,WY,Hot Springs,394.149836,1,5,8,1,11.0,27.0
3129,56019,WY,Johnson,1713.579912,5,7,8,1,8.7,21.1
3130,56021,WY,Laramie,31924.453769,8,65,53,3,10.1,29.7
3131,56023,WY,Lincoln,2478.628436,8,12,22,2,8.6,25.6
3132,56025,WY,Natrona,32267.100162,7,53,64,3,9.0,29.4
3133,56027,WY,Niobrara,544.734192,1,3,3,1,8.4,25.5
3134,56029,WY,Park,5818.211156,4,18,40,3,8.0,25.5
3135,56031,WY,Platte,1798.839152,3,5,13,2,8.8,28.0
3136,56033,WY,Sheridan,12976.661539,6,22,30,2,9.8,23.3
3137,56035,WY,Sublette,1943.267822,3,3,12,1,6.9,23.5
3138,56037,WY,Sweetwater,18934.737809,5,33,32,2,8.1,31.7
3139,56039,WY,Teton,6212.390430,11,23,55,3,4.8,12.7
3140,56041,WY,Uinta,4686.017653,2,16,16,2,9.0,27.9
3141,56043,WY,Washakie,931.411647,2,6,11,2,12.0,27.7
3142,56045,WY,Weston,1237.267037,4,3,11,2,10.0,29.2

In [12]:
access = access.merge(socio_economic, on=["FIPS", "State", "County"], how="outer")
access

,FIPS,State,County,LACCESS_POP15,GROC14,FFR14,FSR14,FMRKT16,PCT_DIABETES_ADULTS13,PCT_OBESE_ADULTS13,MEDHHINC15,POVRATE15
0,1001,AL,Autauga,17496.693038,4,36,29,1,13.0,34.1,56580.0,12.7
1,1003,AL,Baldwin,30561.264430,29,132,221,4,10.4,27.4,52387.0,12.9
2,1005,AL,Barbour,6069.523628,5,22,15,4,18.4,44.4,31433.0,32.0
3,1007,AL,Bibb,969.378841,5,5,5,1,14.8,40.3,40767.0,22.2
4,1009,AL,Blount,3724.428242,6,21,15,1,14.1,34.6,50487.0,14.7
5,1011,AL,Bullock,4141.900365,2,3,1,1,19.6,43.0,28251.0,39.6
6,1013,AL,Butler,1304.328756,3,17,10,2,17.7,36.3,33868.0,25.8
7,1015,AL,Calhoun,27785.986765,27,103,77,2,14.9,32.2,42091.0,20.0
8,1017,AL,Chambers,7131.505717,7,26,16,1,16.4,39.7,35560.0,22.4
9,1019,AL,Cherokee,103.522499,5,15,11,1,13.3,33.6,39144.0,19.4
10,1021,AL,Chilton,1469.899110,6,20,18,0,13.3,35.9,42767.0,20.2
11,1023,AL,Choctaw,2702.895199,3,6,5,1,18.1,40.8,35089.0,24.4
12,1025,AL,Clarke,5712.926332,5,26,15,2,16.3,38.2,37317.0,22.2
13,1027,AL,Clay,642.740920,3,4,6,2,14.6,37.3,38908.0,18.4
14,1029,AL,Cleburne,789.535143,2,8,2,1,12.6,30.0,42136.0,18.9
15,1031,AL,Coffee,10486.085980,5,34,28,1,15.9,33.7,46858.0,16.2
16,1033,AL,Colbert,11095.666304,10,52,38,3,18.7,37.5,41171.0,18.1
17,1035,AL,Conecuh,3558.359440,2,7,4,1,17.4,36.4,29981.0,28.3
18,1037,AL,Coosa,2828.930334,1,1,0,0,17.3,39.7,36078.0,20.3
19,1039,AL,Covington,3769.122248,6,24,18,2,14.7,34.0,36355.0,22.3
20,1041,AL,Crenshaw,5278.966487,3,5,6,1,16.5,39.7,36759.0,19.9
21,1043,AL,Cullman,5900.270202,15,53,48,1,14.4,33.4,39290.0,19.4
22,1045,AL,Dale,14036.970117,8,34,30,2,14.1,36.5,45294.0,18.5
23,1047,AL,Dallas,7640.056868,8,19,15,1,19.0,40.8,29682.0,34.6
24,1049,AL,DeKalb,2679.852662,14,43,31,2,13.4,30.4,37305.0,20.6
25,1051,AL,Elmore,15064.366588,10,45,38,2,13.4,35.4,53548.0,14.0
26,1053,AL,Escambia,5058.775403,4,27,20,3,17.8,37.7,36840.0,24.4
27,1055,AL,Etowah,23289.826821,13,79,57,3,16.8,35.1,42145.0,19.0
28,1057,AL,Fayette,407.386753,5,9,9,1,15.1,33.7,37085.0,20.4
29,1059,AL,Franklin,3663.441736,8,18,16,2,13.9,33.2,38535.0,21.1
...,...,...,...,...,...,...,...,...,...,...,...,...
3113,55129,WI,Washburn,2822.112627,6,5,34,1,10.5,30.8,45043.0,13.5
3114,55131,WI,Washington,25036.823321,18,75,77,5,8.2,29.2,70778.0,5.3
3115,55133,WI,Waukesha,139440.964039,66,258,299,12,7.9,27.5,78689.0,4.7
3116,55135,WI,Waupaca,6215.256992,9,37,49,1,9.9,28.5,54849.0,10.7
3117,55137,WI,Waushara,400.713747,8,8,32,0,10.6,32.9,49912.0,11.8
3118,55139,WI,Winnebago,34475.392629,15,92,123,8,8.6,31.9,52725.0,11.3
3119,55141,WI,Wood,17934.342793,10,41,66,5,8.1,32.3,51025.0,11.3
3120,56001,WY,Albany,13449.746587,3,27,35,2,6.9,23.3,44455.0,20.1
3121,56003,WY,Big Horn,2176.423005,3,5,7,3,11.7,28.9,50056.0,12.1
3122,56005,WY,Campbell,10762.158102,5,33,31,1,7.0,34.3,83042.0,7.5
3123,56007,WY,Carbon,8588.988510,3,7,26,1,8.2,28.2,60209.0,11.4
3124,56009,WY,Converse,1740.297012,3,8,17,1,10.2,28.3,70307.0,8.5
3125,56011,WY,Crook,1795.576875,3,6,13,0,8.9,25.9,64851.0,7.7
3126,56013,WY,Fremont,5269.600430,8,20,39,6,9.6,28.3,52408.0,12.9
3127,56015,WY,Goshen,3457.690654,2,11,12,3,9.0,29.9,48146.0,15.1
3128,56017,WY,Hot Springs,394.149836,1,5,8,1,11.0,27.0,46021.0,11.9
3129,56019,WY,Johnson,1713.579912,5,7,8,1,8.7,21.1,56845.0,8.2
3130,56021,WY,Laramie,31924.453769,8,65,53,3,10.1,29.7,59147.0,10.6
3131,56023,WY,Lincoln,2478.628436,8,12,22,2,8.6,25.6,62364.0,8.8
3132,56025,WY,Natrona,32267.100162,7,53,64,3,9.0,29.4,56703.0,11.0
3133,56027,WY,Niobrara,544.734192,1,3,3,1,8.4,25.5,46693.0,13.3
3134,56029,WY,Park,5818.211156,4,18,40,3,8.0,25.5,55527.0,9.6
3135,56031,WY,Platte,1798.839152,3,5,13,2,8.8,28.0,51863.0,11.7
3136,56033,WY,Sheridan,12976.661539,6,22,30,2,9.8,23.3,57122.0,9.5
3137,56035,WY,Sublette,1943.267822,3,3,12,1,6.9,23.5,77581.0,6.1
3138,56037,WY,Sweetwater,18934.737809,5,33,32,2,8.1,31.7,71867.0,8.5
3139,56039,WY,Teton,6212.390430,11,23,55,3,4.8,12.7,83290.0,6.6
3140,56041,WY,Uinta,4686.017653,2,16,16,2,9.0,27.9,62968.0,9.8
3141,56043,WY,Washakie,931.411647,2,6,11,2,12.0,27.7,56088.0,11.2
3142,56045,WY,Weston,1237.267037,4,3,11,2,10.0,29.2,60986.0,9.8

In [13]:
access.isnull().any().sum()

5

In [14]:
access.dropna(how="any", inplace=True)
access

,FIPS,State,County,LACCESS_POP15,GROC14,FFR14,FSR14,FMRKT16,PCT_DIABETES_ADULTS13,PCT_OBESE_ADULTS13,MEDHHINC15,POVRATE15
0,1001,AL,Autauga,17496.693038,4,36,29,1,13.0,34.1,56580.0,12.7
1,1003,AL,Baldwin,30561.264430,29,132,221,4,10.4,27.4,52387.0,12.9
2,1005,AL,Barbour,6069.523628,5,22,15,4,18.4,44.4,31433.0,32.0
3,1007,AL,Bibb,969.378841,5,5,5,1,14.8,40.3,40767.0,22.2
4,1009,AL,Blount,3724.428242,6,21,15,1,14.1,34.6,50487.0,14.7
5,1011,AL,Bullock,4141.900365,2,3,1,1,19.6,43.0,28251.0,39.6
6,1013,AL,Butler,1304.328756,3,17,10,2,17.7,36.3,33868.0,25.8
7,1015,AL,Calhoun,27785.986765,27,103,77,2,14.9,32.2,42091.0,20.0
8,1017,AL,Chambers,7131.505717,7,26,16,1,16.4,39.7,35560.0,22.4
9,1019,AL,Cherokee,103.522499,5,15,11,1,13.3,33.6,39144.0,19.4
10,1021,AL,Chilton,1469.899110,6,20,18,0,13.3,35.9,42767.0,20.2
11,1023,AL,Choctaw,2702.895199,3,6,5,1,18.1,40.8,35089.0,24.4
12,1025,AL,Clarke,5712.926332,5,26,15,2,16.3,38.2,37317.0,22.2
13,1027,AL,Clay,642.740920,3,4,6,2,14.6,37.3,38908.0,18.4
14,1029,AL,Cleburne,789.535143,2,8,2,1,12.6,30.0,42136.0,18.9
15,1031,AL,Coffee,10486.085980,5,34,28,1,15.9,33.7,46858.0,16.2
16,1033,AL,Colbert,11095.666304,10,52,38,3,18.7,37.5,41171.0,18.1
17,1035,AL,Conecuh,3558.359440,2,7,4,1,17.4,36.4,29981.0,28.3
18,1037,AL,Coosa,2828.930334,1,1,0,0,17.3,39.7,36078.0,20.3
19,1039,AL,Covington,3769.122248,6,24,18,2,14.7,34.0,36355.0,22.3
20,1041,AL,Crenshaw,5278.966487,3,5,6,1,16.5,39.7,36759.0,19.9
21,1043,AL,Cullman,5900.270202,15,53,48,1,14.4,33.4,39290.0,19.4
22,1045,AL,Dale,14036.970117,8,34,30,2,14.1,36.5,45294.0,18.5
23,1047,AL,Dallas,7640.056868,8,19,15,1,19.0,40.8,29682.0,34.6
24,1049,AL,DeKalb,2679.852662,14,43,31,2,13.4,30.4,37305.0,20.6
25,1051,AL,Elmore,15064.366588,10,45,38,2,13.4,35.4,53548.0,14.0
26,1053,AL,Escambia,5058.775403,4,27,20,3,17.8,37.7,36840.0,24.4
27,1055,AL,Etowah,23289.826821,13,79,57,3,16.8,35.1,42145.0,19.0
28,1057,AL,Fayette,407.386753,5,9,9,1,15.1,33.7,37085.0,20.4
29,1059,AL,Franklin,3663.441736,8,18,16,2,13.9,33.2,38535.0,21.1
...,...,...,...,...,...,...,...,...,...,...,...,...
3113,55129,WI,Washburn,2822.112627,6,5,34,1,10.5,30.8,45043.0,13.5
3114,55131,WI,Washington,25036.823321,18,75,77,5,8.2,29.2,70778.0,5.3
3115,55133,WI,Waukesha,139440.964039,66,258,299,12,7.9,27.5,78689.0,4.7
3116,55135,WI,Waupaca,6215.256992,9,37,49,1,9.9,28.5,54849.0,10.7
3117,55137,WI,Waushara,400.713747,8,8,32,0,10.6,32.9,49912.0,11.8
3118,55139,WI,Winnebago,34475.392629,15,92,123,8,8.6,31.9,52725.0,11.3
3119,55141,WI,Wood,17934.342793,10,41,66,5,8.1,32.3,51025.0,11.3
3120,56001,WY,Albany,13449.746587,3,27,35,2,6.9,23.3,44455.0,20.1
3121,56003,WY,Big Horn,2176.423005,3,5,7,3,11.7,28.9,50056.0,12.1
3122,56005,WY,Campbell,10762.158102,5,33,31,1,7.0,34.3,83042.0,7.5
3123,56007,WY,Carbon,8588.988510,3,7,26,1,8.2,28.2,60209.0,11.4
3124,56009,WY,Converse,1740.297012,3,8,17,1,10.2,28.3,70307.0,8.5
3125,56011,WY,Crook,1795.576875,3,6,13,0,8.9,25.9,64851.0,7.7
3126,56013,WY,Fremont,5269.600430,8,20,39,6,9.6,28.3,52408.0,12.9
3127,56015,WY,Goshen,3457.690654,2,11,12,3,9.0,29.9,48146.0,15.1
3128,56017,WY,Hot Springs,394.149836,1,5,8,1,11.0,27.0,46021.0,11.9
3129,56019,WY,Johnson,1713.579912,5,7,8,1,8.7,21.1,56845.0,8.2
3130,56021,WY,Laramie,31924.453769,8,65,53,3,10.1,29.7,59147.0,10.6
3131,56023,WY,Lincoln,2478.628436,8,12,22,2,8.6,25.6,62364.0,8.8
3132,56025,WY,Natrona,32267.100162,7,53,64,3,9.0,29.4,56703.0,11.0
3133,56027,WY,Niobrara,544.734192,1,3,3,1,8.4,25.5,46693.0,13.3
3134,56029,WY,Park,5818.211156,4,18,40,3,8.0,25.5,55527.0,9.6
3135,56031,WY,Platte,1798.839152,3,5,13,2,8.8,28.0,51863.0,11.7
3136,56033,WY,Sheridan,12976.661539,6,22,30,2,9.8,23.3,57122.0,9.5
3137,56035,WY,Sublette,1943.267822,3,3,12,1,6.9,23.5,77581.0,6.1
3138,56037,WY,Sweetwater,18934.737809,5,33,32,2,8.1,31.7,71867.0,8.5
3139,56039,WY,Teton,6212.390430,11,23,55,3,4.8,12.7,83290.0,6.6
3140,56041,WY,Uinta,4686.017653,2,16,16,2,9.0,27.9,62968.0,9.8
3141,56043,WY,Washakie,931.411647,2,6,11,2,12.0,27.7,56088.0,11.2
3142,56045,WY,Weston,1237.267037,4,3,11,2,10.0,29.2,60986.0,9.8

In [15]:
access.describe()

,FIPS,LACCESS_POP15,GROC14,FFR14,FSR14,FMRKT16,PCT_DIABETES_ADULTS13,PCT_OBESE_ADULTS13,MEDHHINC15,POVRATE15
count,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000
mean,30364.400000,19307.368121,21.107372,73.194551,76.475321,2.747756,11.230481,31.015224,48586.288462,16.265096
std,15154.475947,47830.775929,90.684955,255.601242,259.569327,5.825189,2.481946,4.519136,12262.117235,6.433507
min,1001.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.300000,11.800000,22894.000000,3.400000
25%,18178.500000,1632.491143,3.000000,5.000000,7.000000,0.000000,9.500000,28.300000,40447.750000,11.500000
50%,29176.000000,4131.174278,5.000000,15.000000,17.000000,1.000000,11.100000,31.200000,46803.500000,15.200000
75%,45073.500000,13174.899203,12.000000,44.000000,49.000000,3.000000,12.900000,33.800000,54175.250000,19.700000
max,56045.000000,740267.412661,2429.000000,7798.000000,7821.000000,125.000000,23.500000,47.600000,125900.000000,47.400000